name: Cop
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Rubocop checks
        uses: gimenete/rubocop-action@1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Setup Redis
        run: |
          sudo apt-get install redis-server
      - name: Stop|Start Redis
        run: |
          sudo service redis-server stop
          redis-server --daemonize yes
      - name: Bundler
        run: |
          gem install bundler
          bundle install
      - name: Rails Test
        run: |
          bundle exec rake test
      - name: Stop Redis
        run: |
          sudo /etc/init.d/redis-server stop
