name: Cop
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Rubocop checks
        uses: gimenete/rubocop-action@1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Rails Test
        run: |
          gem install bundler
          bundle install
          bundle exec rake test